name: Update Lotto Data

on:
  schedule:
    - cron: '0 22 * * 6'  # 매주 토요일 22:00 (KST)
  workflow_dispatch:  # 수동 실행 가능

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 저장소 내용 쓰기 권한 명시적 부여
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 전체 히스토리 가져오기 (중요)

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install axios cheerio iconv-lite

      - name: Create data directory if not exists
        run: mkdir -p data/backups

      - name: Initialize data file if not exists
        run: |
          if [ ! -f "data/lotto-data.json" ]; then
            echo "[]" > data/lotto-data.json
            echo "Created empty data file"
          fi

      - name: Pull latest changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull origin main --rebase

      - name: Update lotto data
        run: |
          # 로또 데이터 업데이트 스크립트 실행
          node .github/scripts/update-lotto.js

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update lotto data - 자동 업데이트"
          file_pattern: "data/lotto-data.json data/backups/*"
